### ISSUE TITLE
v2 Ideas about next version

### ISSUE THREAD

**Issue by linuxenko** [linuxenko/cakejs2#1]
- Run loop implementation like (emberjs runloop)

> https://guides.emberjs.com/v1.10.0/understanding-ember/run-loop/
- Template engine check (preferable handlebars)

> https://github.com/livoras/virtual-template
> https://github.com/wycats/handlebars.js
> https://github.com/substack/hyperx
> HyperX usage example https://github.com/feross/webtorrent-app
- Check out observable objects 

> http://arv.github.io/ecmascript-object-observe/
> https://github.com/Polymer/observe-js

**Comment by linuxenko** [comment]
* Templating

**Comment by dsc0d3** [comment]
Ember Run Loop Handbook

> https://github.com/dsc0d3/ember-runloop-handbook

Virtual dom

> https://facebook.github.io/react/docs/working-with-the-browser.html
